title: Dev and Such
description: >- # this means to ignore newlines until "baseurl:"
  A blog in which I discuss things related to programming,
  development, software, and tech in general.
url: "https://echosa.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repository: "echosa/echosa.github.io"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
permalink: /blog/:year/:month/:day/:title/
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
tag_archive:
  type: liquid
  path: /tags/
paginate: 5
paginate_path: /page:num/
include: ["_pages"]
search: true
