title: Dev and Such
description: >- # this means to ignore newlines until "baseurl:"
  A blog in which I discuss things related to programming,
  development, software, and tech in general.
url: "https://echosa.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repository: "echosa/echosa.github.io"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
permalink: /:categories/:year/:month/:day/:title/
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      comments: true
      share: true
      related: true
      author_profile: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
tag_archive:
  type: liquid
  path: /tags/
paginate: 5
paginate_path: /page:num/
include: ["_pages"]
search: true
author:
  name: "Brian Zwahr"
  bio: "We learn from our mistakes. Learn from mine, too!"
  location: "USA"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/echosa"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/echosa"
comments:
  provider: "staticman_v2"
staticman:
  branch: "master"
  endpoint: "https://dev.staticman.net/v3/entry/github/"
  moderation: true
